import React from 'react'
import { Box, Email, Image, Item, Span, A } from '../src'

const email = (
  <Email title="Test Email">
    <Item>
      <Span fontSize={15}>Hello, world!</Span>
    </Item>
    <Item>
      <Box cellSpacing={20} width="100%" style={{ borderTop: '3px solid black' }}>
        <Item>
          <Span color="gray" lineHeight={20}>Generated by <A href="https://github.com/chromakode/react-html-email">react-html-email</A></Span>
          <Image src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/React.js_logo.svg/100px-React.js_logo.svg.png" width={100} height={100} />
        </Item>
      </Box>
    </Item>
  </Email>
)

export default email
